apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: demo
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: ZGVtb3VzZXI=
  POSTGRES_PASSWORD: ZGVtb3Bhc3M=
  POSTGRES_DB: ZGVtb2Ri
